# Generated by Django 3.2.5 on 2022-08-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_search', '0047_alter_logindexset_bcs_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesearch',
            name='space_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='空间唯一标识'),
        ),
        migrations.AddField(
            model_name='logindexset',
            name='space_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='空间唯一标识'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='space_uid',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='空间唯一标识'),
        ),
        migrations.AddField(
            model_name='resourcechange',
            name='space_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='空间唯一标识'),
        ),
    ]
